#coding:utf8
#
LANG_INVALID_ROLE = '不存在的角色';
LANG_CALCGOLDFAILED = '同步金子经验失败';
LANG_NOTENOUGHGOLD = '金子不够';
LANG_NOTENOUGHLV = '等级不够';
LANG_LVMAX = "已经达到最高等级";
LANG_NOTENOUGHEXP = "经验不够";
LANG_SKILLLVMAX = "技能已经达到最高等级";
LANG_SKILLREQHIGHERLV = "升级所需主角等级不足";
LANG_PETSKILLREQHIGHERLV = "升级所需宠物等级不足";
LANG_SKILLREQHIGHERGOLD = "升级所需金子不足";
LANG_PETOPENLV = "需要主角升级到10级才能开启";
LANG_PETLVUPNEEDEXP = "升级宠物需要的经验不足";
LANG_STUDYSKILLSUCCEED = "学习技能成功";
LANG_STUDYSKILLFAILED = "学习技能失败";
LANG_LVUPSKILLSUCCEED = "升级技能成功";
LANG_LVUPSKILLFAILED = "升级技能失败";
LANG_USESKILLSUCCEED = "设置技能使用顺序成功";
LANG_USESKILLFAILED = "设置技能使用顺序失败";